apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - image: busybox:1.28
    name: busy
    command: ['sh','-c','sleep 5000']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
